class Convert
  def initialize: (Float value) -> void
  def meters_to_kilometers: -> ::Float
  def meters_to_miles: -> ::Float
  def kilometers_to_miles: -> ::Float
  def kilometers_to_meters: -> ::Float
  def miles_to_meters: -> ::Float
  def miles_to_kilometers: -> ::Float
end